# Generated by Django 5.2.5 on 2025-10-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='colorHex',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='category', max_length=50),
        ),
    ]
