# Generated by Django 5.2.5 on 2025-10-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_recurringtransaction_account_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='last_processed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10),
        ),
    ]
